if (typeof module !== 'undefined' && module.exports) { module.exports = { CAMPAIGN, campaignEnsure, campaignStatus, campaignEligibility, campaignStart, campaignSettle, threadUsage, joinMarionette, processSpiritThreads, applySpiritThread, powerEffect, actionDisabled, resolveIncoming, beginTurn, tauntFilter, statusResistChance, unlockedAbilities, activeSpecs, chooseStructuredAbility, abilityEffects, applyStructuredAbility, passiveCombatModifier, attackOnce, v15Damage, combatRates, tickCombatEffectDurations, applyPassiveAuras, hasStatus, addStatus, makeEnemy, statsAtSequence, awakenStats, makeAgent, advanceStats, COMBAT_BALANCE, STAT_TABLE, PATH_ARCHETYPE, archetypeOf, tableStats, basePathSpeed, statsFromVariance, restatAgent, SAVE_VERSION, PATHS, PATH_KEYS, PATH_GROWTH, PATH_METERS, BASE_STAT_PROFILES, PATH_COUNTERS, PATH_METERS, WEAPONS, tierFor, nextTier, authorityTier, authorityGap, pathMatchup, threadSlots, threadRange, makeAgent, makeEnemy, awakenStats, statsAtSequence, makeQuest, makeQuestBoard, questCountForReputation, resolveQuest, groupEventsToRows, abbrNum, summarizeBattleEvents, newGame, migrateSave, attemptTraining, canTrain, digestGain, effectiveStats, applyConsequences, pathOf, unlockedAbilities, saveGame, loadGame, specialStatFor, maxSPFor, damageMultiplier, processSpiritThreads, speedFor, actionValueFor, combatRates, addStatus, processStatuses, applySpiritThread, getMeterValue, setMeterValue, changeMeter, addMarionettes }; }

if (typeof module !== 'undefined' && module.exports) Object.assign(module.exports, { makeCombatUnit, getCombatAgent, effectiveAbilityCost, attackHit, consumeAttackMiss, consumeCritFailure, combatResistances, canonicalResistanceElement, tickUnitStatuses, tryRevive, tryMythicalForm, maybeCounter });
if (typeof module !== 'undefined' && module.exports) Object.assign(module.exports, { recoverHP, canGainShield, setCombatDuration, settleFatalDamage });

if (typeof module !== 'undefined' && module.exports) Object.assign(module.exports, { abilityDescription, abilityDamageText, isPhase3DeferredAbility, applyPartyPassiveEffects, initiativeScore, unitInitiative });

if (typeof module !== 'undefined' && module.exports) Object.assign(module.exports, { signatureUseful, signatureSupportTypes, signatureCastCost, signatureTryAction, signatureReady, signaturePrepareCast, applySignatureEffect, signatureAfterCast, signatureAfterDamage, signatureTurnStart, signatureTurnEnd, signatureFinalDeath, signatureActionFinished, signatureBorrowedAbilities, signatureDescription, signatureRetryContest, signatureCreateCompanion, signatureCaptureSoul, combatResourceSnapshot, emitCombatResources });
if (typeof module !== 'undefined' && module.exports) Object.assign(module.exports, { MYTHICAL_AUTHORITIES, mythicalAwaken, mythicalTurnStart, mythicalTurnEnd, mythicalBeforeDamage, mythicalAfterDamage, mythicalBeforeFatal, mythicalFinalDeath, mythicalBeforeCast, mythicalAfterCast, mythicalTryAction, mythicalDamageOptions, mythicalDescription });
