// Phase 4 signatures use owned combat state and the same numeric rules as their descriptions.
const SIGNATURE_DEFAULTS=Object.freeze({chargeCost:100,duration:2,amount:.5,uses:1,
 door_record:{multiplier:1},error_theft:{duration:1},error_distortion:{duration:2,chargeCost:0},error_parasite:{drain:20},
 visionary_hypnosis:{duration:1},darkness_nightmare:{amount:.75},death_summon:{duration:3,amount:.5},
 giant_guardian:{amount:.2},red_war_command:{amount:.5},sun_purify:{amount:1},tyrant_lightning:{amount:.5},
 demoness_affliction:{duration:2},fortune_retry:{duration:2},fortune_calamity:{amount:.75},
 mother_seed:{duration:3,amount:.08},moon_medicine:{amount:.15},moon_beast:{duration:3,amount:.5},
 moon_blood:{amount:.15},paragon_device:{duration:3,amount:.5},abyss_desire:{amount:.5},chained_release:{amount:.3}});
function signatureRule(e){return {...SIGNATURE_DEFAULTS,...(SIGNATURE_DEFAULTS[e.rule]||{}),...e};}
function signatureEffects(spec){return abilityEffects(spec).filter(e=>e.type==='signature');}
function signatureDescription(effect){const e=signatureRule(effect),p=n=>`${Math.round(n*100)}%`,spend=`At ${e.chargeCost} charge, `,turn=`${e.duration} turn${e.duration===1?'':'s'}`;
 const text={
 thread_binding:`Five binding stages; losing more than ${p(e.damageBreakThreshold??.30)} Max HP in one action removes one stage. At ${e.chargeCost} charge, attachment resistance falls by ${Math.round(Number(e.resistancePenetration??.20)*100)} percentage points, with no minimum resistance.`,
 door_record:`Witness enemy abilities from Sequence 6; keep one record at Sequence 6, four from Sequence 5. ${spend}replay one record at full strength, paying its original SP cost and cooldown.`,
 error_theft:`${spend}steal one witnessed ability from Sequence 6: deny its owner access for ${turn} and gain one normally paid use.`,
 error_distortion:`Distort one enemy's next paid damaging ability to target its own side, once within ${turn}; normal SP, cooldown, damage and hit rules remain. Confusion immunity and mental resistance apply.`,
 error_parasite:`Attach one parasite from Sequence 4 for ${turn}; on each host turn siphon ${Number(effect.drain??effect.amount??20)} SP actually available and recover ${p(e.maxHpRatio??0)} Max HP when SP is drained.`,
 visionary_hypnosis:`Apply resistible hypnosis for ${turn}. ${spend}command the victim's next action against its own side.`,
 darkness_nightmare:`${spend}enter an already sleeping enemy's dream for ${p(e.amount)} INT Psychic damage without waking it. Shared accuracy, Dodge and forced-miss rules apply. Waking breaks dream access.`,
 death_summon:`Summon one undead companion for ${turn}, with ${p(e.amount)} of the owner's ATK and INT. ${spend}sustain the companion.`,
 giant_guardian:`${spend}protect allies with ${p(e.amount)} Max HP shields and ready one retaliatory strike for ${turn}.`,
 red_war_command:`${spend}ready one allied follow-up per living ally, at ${p(e.amount)} of the commander's ATK, for ${turn}.`,
 sun_purify:`Holy damage and purification build Radiance. ${spend}cleanse ${e.amount} additional Poison or Curse effect per ally and strip one enemy dark protection.`,
 tyrant_soaked:`Apply Soaked for ${turn}. Lightning consumes it.`,tyrant_lightning:`${spend}consume Soaked and chain ${p(e.amount)} INT Lightning damage to one additional foe.`,
 demoness_affliction:`Curse ticks build a separate Affliction charge. From Sequence 5, ${spend}spread one existing curse to one other foe for ${turn}; spread cannot repeat itself.`,
 fortune_retry:`${spend}retry one failed hit contest using the same chance for ${turn}; forced misses still apply.`,
 fortune_calamity:`Mark misfortune for ${turn}: a failed attack or damaging ability causes ${p(e.amount)} of the caster's INT as Psychic backlash, once per action.`,
 fortune_rewind:'Restore HP and temporary buffs from two rounds earlier; preserve SP, cooldowns, survival counters and form uses. Healing prohibition blocks HP recovery.',
 emperor_redirect:`${spend}redirect one enemy heal, shield or stat buff to yourself within ${turn}; offensive effects remain unchanged.`,
 justiciar_prohibition:`For ${turn}, prohibit enemy healing and shields. Violating actions pay their normal costs and trigger a judgment; full charge strengthens one judgment.`,
 hanged_graze:`From Sequence 5, retain one final defeated Beyonder's eligible ability. ${spend}release one normally paid use of the grazed soul.`,
 hermit_scroll:`From Sequence 6, prepare one owned spell scroll. ${spend}release it at full strength with original SP cost independently of its source cooldown.`,
 tower_imitation:`From Sequence 6, analyze an enemy ability cast twice. ${spend}imitate it at full strength with its original SP cost and cooldown; no record book.`,
 paragon_device:`Deploy one device for ${turn}, with ${p(e.amount)} of your ATK and INT. ${spend}renew its lifetime.`,
 mother_seed:`Plant one seed on the most injured living ally for ${turn}; restore ${p(e.amount)} Max HP on each turn. ${spend}double one seed's regeneration.`,
 moon_medicine:`Carry two medicine doses, each restoring ${p(e.maxHpRatio??.12)} Max HP to the most injured ally. ${spend}replenish one dose and restore an extra ${p(e.amount)} Max HP to the most injured ally.`,
 moon_beast:`Command one beast companion for ${turn} with ${p(e.amount)} of your ATK and INT.`,
 moon_blood:`Sanguine powers begin at Sequence 7. ${spend}restore ${p(e.amount)} Max HP to the most injured living ally.`,
 abyss_desire:`From Sequence 5, mark one enemy for ${turn}. Its actual paid SP grows Desire; ${spend}detonate ${p(e.amount)} INT plus its paid SP as Fire damage. Shared accuracy, Dodge and forced-miss rules apply.`,
 chained_release:`Contain one self-inflicted Curse for ${turn}. ${spend}remove it and release ${p(e.amount)} Max HP as Dark damage.`};
 if(!text[e.rule])throw new Error(`Unknown signature rule: ${e.rule}`);return text[e.rule];}
function signatureUnits(state){return [...(state?.allies||[]),...(state?.enemies||[])];}
function signatureUnit(agent,state){return signatureUnits(state).find(u=>u.id===agent.id);}
function signatureLog(actor,state,lines,text,extra={}){lines.push({text,kind:'quirk'});emitCombatEvent(state,{type:'status',subtype:'signature',actorId:actor.id,actorName:actor.name,actorTeam:teamOf(actor,state),text,...extra});}
function signatureBonus(actor,state){if(!actor||actor.summoned)return;const a=getCombatAgent(actor),round=state?.currentRound||1;if(a._signatureGainRound===round)return;a._signatureGainRound=round;changeMeter(a,a.path,Number(PATH_METERS[a.path]?.gainSignature??10));}
function signatureSpend(actor,e,state,lines){const a=getCombatAgent(actor),cost=Number(e.chargeCost??100);if(getMeterValue(a,a.path)<cost)return false;changeMeter(a,a.path,-cost);signatureLog(actor,state,lines,`${actor.name} spends ${cost} ${PATH_METERS[a.path]?.name||'charge'}.`);return true;}
function signatureDamage(actor,target,multiplier,element,state,lines,r,amount=null){if(!actor?.alive||!target?.alive)return null;const a=getCombatAgent(actor),damage=amount==null?v15Damage('pure_caster_ability',{agent:a,actor,target,abilityMult:multiplier,damageSpec:{scaling:'INT',multiplier,type:'elemental',element}}):Math.max(0,Math.round(amount));
 const hit=resolveIncoming(actor,target,damage,state,lines,r,{damageType:element,signature:true,indirect:true});emitCombatEvent(state,{type:'damage',actorId:actor.id,actorName:actor.name,actorTeam:teamOf(actor,state),targetId:target.id,targetName:target.name,targetTeam:teamOf(target,state),ability:'Signature',amount:hit.hpLoss+hit.absorbed,hpLoss:hit.hpLoss,absorbed:hit.absorbed,shieldAfter:target.shield||0,hpAfter:target.hp,maxHp:target.maxHp,damageType:element,isSignature:true});return hit;}
function signatureHeal(actor,target,amount,state,lines){const healed=recoverHP(target,amount);if(healed){signatureBonus(actor,state);emitCombatEvent(state,{type:'heal',actorId:actor.id,actorName:actor.name,actorTeam:teamOf(actor,state),targetId:target.id,targetName:target.name,targetTeam:teamOf(target,state),amount:healed,hpAfter:target.hp,maxHp:target.maxHp});}return healed;}
function signatureEligible(entry,owner,source){const spec=entry?.spec||entry,id=spec?.effectId||spec?.id;if(!spec||spec.type!=='active'||!id||spec._signatureOwned||spec._signatureCopied)return false;
 if(abilityEffects(spec).some(e=>['signature','copy_ability','revive','extra_turn','form'].includes(e.type)))return false;
 if(['thread_binding','time_theft','combat_record','spell_imitation'].includes(id))return false;
 const original=entry.sequence??spec._signatureSourceSequence??pathOf(source?.path)?.sequences?.find(t=>(t.abilities||[]).some(s=>(s.effectId||s.id)===id))?.sequence??source?.sequence;
 return Number.isInteger(original)&&original>=owner.sequence;
}
function signatureObserved(actor,enemy,state,repeated=false){const a=getCombatAgent(actor),foes=foesOf(actor,state),ordered=[enemy,...foes.filter(x=>x!==enemy)].filter(Boolean);for(const unit of ordered){const log=state?._abilityHistoryByUnit?.[unit.id]||[];for(let i=log.length-1;i>=0;i--){const entry=log[i];if(!signatureEligible(entry,a,unit))continue;const id=entry.spec.effectId||entry.spec.id;if(repeated&&log.filter(x=>(x.spec.effectId||x.spec.id)===id).length<2)continue;return {spec:cloneE(entry.spec),sourceId:unit.id,sequence:entry.sequence??signatureSourceRank(entry.spec,unit)};}}return null;}
function signatureSourceRank(spec,source){return spec._signatureSourceSequence??pathOf(source?.path)?.sequences?.find(t=>(t.abilities||[]).some(s=>(s.effectId||s.id)===(spec.effectId||spec.id)))?.sequence??source?.sequence;}
function signatureOwned(source,owner,kind){const spec=cloneE(source.spec||source);spec._signatureOwned=kind;spec._signatureOwnerId=owner.id;spec._signatureSourceId=source.sourceId;spec._signatureSourceSequence=source.sequence;spec.id=spec.effectId=`${kind}:${spec.effectId||spec.id}`;return spec;}
function signatureBorrowedAbilities(agent){const result=[];if(agent._signatureImitation)result.push(signatureOwned(agent._signatureImitation,agent,'mythical_imitation'));if(agent._signatureBorrowed)result.push(signatureOwned(agent._signatureBorrowed,agent,'error'));if(agent._signatureSoul&&getMeterValue(agent,agent.path)>=100)result.push(signatureOwned(agent._signatureSoul,agent,'soul'));return result;}
function signatureCopySource(agent,spec,enemy,state){agent=getCombatAgent(agent);const actor=signatureUnit(agent,state);if(!actor)return null;for(const e of signatureEffects(spec)){
 if(e.rule==='door_record'&&agent._signatureRecords?.length)return {source:agent._signatureRecords[0],kind:'record',effect:e};
 if(e.rule==='tower_imitation'){const source=signatureObserved(actor,enemy,state,true);if(source)return {source,kind:'imitation',effect:e};}
 if(e.rule==='hermit_scroll'&&agent._signatureScroll&&getMeterValue(agent,agent.path)>=Number(e.chargeCost??100))return {source:agent._signatureScroll,kind:'scroll',effect:e};
 if(e.rule==='hanged_graze'&&agent._signatureSoul&&getMeterValue(agent,agent.path)>=Number(e.chargeCost??100))return {source:agent._signatureSoul,kind:'soul',effect:e};
 }return null;}
function signatureCastCost(agent,spec,enemy,state){const copy=signatureCopySource(agent,spec,enemy,state);return effectiveAbilityCost(getCombatAgent(agent),copy?copy.source.spec:spec);}
function signatureTimed(unit,key,value){unit[key]=value;unit._signatureGrace=unit._signatureGrace||{};unit._signatureGrace[key]=!!unit._acting;return value;}
function signatureDamaging(spec,actor,enemy){if((spec.damage?.multiplier||spec.scale||0)>0||abilityEffects(spec).some(e=>e.type==='damage_component'))return true;const agent=getCombatAgent(actor);for(const e of signatureEffects(spec)){if(getMeterValue(agent,agent.path)<Number(e.chargeCost??100))continue;if(e.rule==='abyss_desire'&&enemy?._signatureDesire?.ownerId===actor.id&&agent.sequence<=5)return true;if(e.rule==='darkness_nightmare'&&(hasStatus(enemy,'sleep')||abilityEffects(spec).some(s=>s.type==='status'&&s.status==='sleep')))return true;}return false;}
function signatureSupportTypes(spec){const types=new Set();for(const e of abilityEffects(spec)){if(['heal','shield','buff'].includes(e.type))types.add(e.type);if(e.type==='heal_damage_ratio'||(e.type==='lifesteal'&&e.duration===undefined))types.add('heal');if(e.type!=='signature')continue;if(['moon_medicine','moon_blood','mother_seed'].includes(e.rule))types.add('heal');if(e.rule==='giant_guardian')types.add('shield');}return [...types];}
function signatureHealableAllies(actor,state){return sameSideOf(actor,state).filter(u=>u.alive&&!hasStatus(u,'no_heal'));}
function signatureUseful(actor,spec,enemy,state){const agent=getCombatAgent(actor),charge=getMeterValue(agent,agent.path);for(const e of signatureEffects(spec)){
 const full=charge>=Number(e.chargeCost??100);
 if(['moon_medicine','mother_seed'].includes(e.rule)){const wounded=signatureHealableAllies(actor,state).some(u=>u.hp<u.maxHp);if(!wounded)return false;if(e.rule==='mother_seed'&&actor._signatureSeedTargetId&&!full){const seeded=signatureUnits(state).find(u=>u.id===actor._signatureSeedTargetId);if(seeded?._signatureSeed?.turns>1)return false;}}
 if(e.rule==='error_distortion'&&enemy?._signatureDistortion?.turns>1)return false;
 if(e.rule==='visionary_hypnosis'&&(enemy?._signatureCommand||hasStatus(enemy,'stunned')))return false;
 if(e.rule==='darkness_nightmare'&&hasStatus(enemy,'sleep')&&!full)return false;
 if(e.rule==='fortune_calamity'&&enemy?._signatureCalamity?.turns>1)return false;
 if(e.rule==='error_parasite'&&actor._signatureParasite?.hostId===enemy?.id&&actor._signatureParasite.turns>1)return false;
 if(e.rule==='emperor_redirect'&&!full&&enemy?._debuffs?.atk<=.8)return false;
 if(e.rule==='justiciar_prohibition'){if(enemy?._signatureProhibition?.turns>1)return false;const candidates=enemy?unlockedAbilities(getCombatAgent(enemy)):[];if(!candidates.some(s=>s.type==='active'&&signatureSupportTypes(s).some(t=>['heal','shield'].includes(t))))return false;}
 }return true;}
function signatureReady(agent,spec,enemy,state){agent=getCombatAgent(agent);const actor=signatureUnit(agent,state),id=spec.effectId||spec.id;if(actor?._signatureDeniedSkills?.[id]>0)return false;if(spec._signatureOwned&&spec._signatureOwnerId!==agent.id)return false;
 for(const e of signatureEffects(spec)){if(e.rule==='door_record'&&(agent.sequence>6||!(agent._signatureRecords?.length)||getMeterValue(agent,agent.path)<Number(e.chargeCost??100)))return false;
 if(e.rule==='tower_imitation'&&(agent.sequence>6||getMeterValue(agent,agent.path)<Number(e.chargeCost??100)||!actor||!signatureObserved(actor,enemy,state,true)))return false;
 if(e.rule==='error_theft'&&(agent.sequence>6||agent._signatureBorrowed||getMeterValue(agent,agent.path)<Number(e.chargeCost??100)||!actor||!signatureObserved(actor,enemy,state)))return false;
 if(e.rule==='error_parasite'&&enemy?.id===agent.id&&!((spec.damage?.multiplier||spec.scale||0)>0||abilityEffects(spec).some(x=>x.type==='damage_component')))return false;
 if(e.rule==='moon_blood'&&agent.sequence>7)return false;
 if(['death_summon','paragon_device','moon_beast'].includes(e.rule)){const companion=signatureUnits(state).find(u=>u.id===actor?._signatureCompanionId&&u.alive);if(companion&&(getMeterValue(agent,agent.path)<Number(e.chargeCost??100)||companion._signatureLifetime>=Number(e.duration??3)))return false;}
 if(e.rule==='fortune_rewind'&&!actor?._signatureHistory?.some(h=>h.round<=(state.currentRound||1)-2))return false;
 if(e.rule==='moon_medicine'&&(actor?._signatureMedicine??2)<=0&&getMeterValue(agent,agent.path)<Number(e.chargeCost??100))return false;}
 const copy=signatureCopySource(agent,spec,enemy,state);if(copy){const owned=signatureOwned(copy.source,agent,copy.kind);if(agent.cooldowns?.[owned.effectId]>0)return false;}return true;
}
function signatureDeceptionState(unit){return JSON.stringify({hp:unit.hp,shield:unit.shield||0,sp:getCombatAgent(unit).sp,status:unit.status,statusMeta:unit.statusMeta,fx:unit._fx,nextMiss:unit._nextAttackMiss,nextCrit:unit._nextCritFail,misfire:unit._skillMisfireChance,cost:unit._spCostMultiplier,cooldown:unit._cooldownPenalty,skip:unit._skipTurns,hit:unit._hitChanceDebuff});}
function signatureOwnDeceptionState(unit){return JSON.stringify({hp:unit.hp,shield:unit.shield||0,fx:unit._fx,reflect:unit._reflect,extra:unit._extraTurns});}
function signaturePrepareCast(agent,actor,enemy,state,lines,r,spec){if(!signatureReady(agent,spec,enemy,state))return null;let owned=cloneE(spec);actor._signatureEventStart=state?.events?.length||0;if(agent.path==='error'){actor._signatureBeforeDeception={foes:Object.fromEntries(foesOf(actor,state).map(u=>[u.id,signatureDeceptionState(u)])),own:signatureOwnDeceptionState(actor)};}
 let source=null,kind=null,effect=null;
 for(const e of signatureEffects(owned)){if(e.rule==='door_record'){source=agent._signatureRecords[0];kind='record';effect=e;}
 else if(e.rule==='tower_imitation'){source=signatureObserved(actor,enemy,state,true);kind='imitation';effect=e;}
 else if(e.rule==='hermit_scroll'&&agent.sequence<=6&&agent._signatureScroll&&getMeterValue(agent,agent.path)>=Number(e.chargeCost??100)){source=agent._signatureScroll;kind='scroll';effect=e;}
 else if(e.rule==='hanged_graze'&&agent._signatureSoul&&getMeterValue(agent,agent.path)>=Number(e.chargeCost??100)){source=agent._signatureSoul;kind='soul';effect=e;}}
 if(source){owned=signatureOwned(source,agent,kind);owned._signatureChargeCost=Number(effect.chargeCost??100);owned._signatureCopied=true;}
 const prohibited=actor._signatureProhibition;if(prohibited){const support=signatureSupportTypes(owned),blocked=support.filter(t=>['heal','shield'].includes(t));if(blocked.length){owned.effects=abilityEffects(owned).filter(e=>!signatureSupportTypes({effects:[e]}).some(t=>blocked.includes(t)));owned._signatureViolation=prohibited.ownerId;if(!owned.effects.length&&!owned.damage)owned._signatureCancelled=true;}}
 for(const foe of foesOf(actor,state)){if(!foe.alive||!foe._signatureRedirect)continue;if(!signatureSupportTypes(owned).length)continue;owned._signatureRedirectTarget=foe.id;owned._signatureRedirectOwner=foe.id;break;}
 if(actor._signatureDistortion&&signatureDamaging(owned,actor,enemy)){const ally=sameSideOf(actor,state).find(u=>u!==actor&&u.alive&&u.inCombat!==false&&!hasStatus(u,'untargetable'))||actor;owned._signatureOffensiveTarget=ally.id;owned._signatureConsumeDistortion=true;}
 if(owned._signatureOwned==='error'&&!agent._signatureBorrowed)return null;if(owned._signatureOwned==='mythical_imitation'&&!agent._signatureImitation)return null;
 if(owned._signatureOwned&&Number(agent.cooldowns?.[owned.effectId||owned.id]||0)>0)return null;
 if(owned._signatureOwned==='soul'){if(!agent._signatureSoul||getMeterValue(agent,agent.path)<100)return null;owned._signatureChargeCost=100;}
 return owned;
}
function signatureCreateCompanion(owner,state,lines,kind='device',duration=3,strength=.5){const a=getCombatAgent(owner);const old=signatureUnits(state).find(u=>u.id===owner._signatureCompanionId);if(old){old.alive=false;old.inCombat=false;}state._signatureSummonSerial=(state._signatureSummonSerial||0)+1;
 const hp=Math.max(1,Math.round(owner.maxHp*.25)),source={id:`signature_${owner.id}_${state._signatureSummonSerial}`,name:`${owner.name}'s ${kind}`,path:a.path,sequence:a.sequence,awakened:false,trait:a.trait,stats:{hp,atk:Math.max(1,Math.round(a.stats.atk*strength)),def:Math.max(1,Math.round(a.stats.def*.5)),int:Math.max(1,Math.round(a.stats.int*strength))},weaponId:'none',weaponMastery:{},injuries:0,sp:0,maxSP:0,cooldowns:{},status:[],alive:true};
 const u=makeCombatUnit(source);u.summoned=true;u._signatureOwnerId=owner.id;u._signatureCompanionKind=kind;u._signatureLifetime=Math.max(1,duration);u._formUsed=u.agent._formUsed=true;u.agent._teamDamageMultiplier=a._teamDamageMultiplier||1;owner._signatureCompanionId=u.id;sameSideOf(owner,state).push(u);signatureLog(owner,state,lines,`${owner.name} creates one ${kind} for ${duration} turns.`);return u;}
function signatureCaptureSoul(owner,victim,state,lines){if(!owner.alive||owner.sequence>5||victim.summoned||!victim.path)return false;const entries=state?._abilityHistoryByUnit?.[victim.id]||[];let entry=entries.findLast(x=>signatureEligible(x,getCombatAgent(owner),victim));if(!entry){const s=unlockedAbilities(getCombatAgent(victim)).find(x=>signatureEligible({spec:x},getCombatAgent(owner),victim));if(s)entry={spec:s};}if(!entry)return false;getCombatAgent(owner)._signatureSoul={spec:cloneE(entry.spec),sourceId:victim.id,sequence:entry.sequence??signatureSourceRank(entry.spec,victim)};signatureBonus(owner,state);signatureLog(owner,state,lines,`${owner.name} grazes one final defeated soul.`);return true;}
function applySignatureEffect(effect,agent,actor,targets,state,lines,r,spec){const e=signatureRule(effect),target=targets.find(t=>t?.alive),allies=sameSideOf(actor,state).filter(u=>u.alive),foes=foesOf(actor,state).filter(u=>u.alive),redirect=spec?._signatureRedirectTarget&&signatureUnits(state).find(u=>u.id===spec._signatureRedirectTarget),weakest=redirect||signatureHealableAllies(actor,state).slice().sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0]||actor;
 switch(e.rule){
 case 'thread_binding':break;
 case 'door_record':case 'tower_imitation':break;
 case 'error_theft':if(target&&agent.sequence<=6&&getMeterValue(agent,agent.path)>=e.chargeCost){const observed=signatureObserved(actor,target,state);if(observed&&signatureSpend(actor,e,state,lines)){agent._signatureBorrowed=observed;const source=signatureUnits(state).find(u=>u.id===observed.sourceId);source._signatureDeniedSkills=source._signatureDeniedSkills||{};source._signatureDeniedSkills[observed.spec.effectId||observed.spec.id]=e.duration;actor._signatureSuccessful=true;signatureBonus(actor,state);signatureLog(actor,state,lines,`${actor.name} steals one paid use; ${source.name} loses that skill for ${e.duration} turn.`);}}break;
 case 'error_distortion':if(target&&!statusImmune(target,'confused')&&r()>=Number(combatRates(getCombatAgent(target)).resistance||0)&&r()>=statusResistChance(target,'confused')){signatureTimed(target,'_signatureDistortion',{ownerId:actor.id,turns:e.duration});addStatus(target,'distorted_logic',e.duration,actor.name);actor._signatureSuccessful=true;signatureBonus(actor,state);signatureLog(actor,state,lines,`${target.name}'s next paid damaging ability will be distorted onto its own side.`);}break;
 case 'error_parasite':e.drain=Number(effect.drain??effect.amount??20);if(target&&target.id!==actor.id&&agent.sequence<=4){const previous=signatureUnits(state).find(u=>u.id===actor._signatureParasite?.hostId);if(previous)previous._signatureParasites=(previous._signatureParasites||[]).filter(p=>p.ownerId!==actor.id);signatureTimed(actor,'_signatureParasite',{hostId:target.id,turns:e.duration});target._signatureParasites=(target._signatureParasites||[]).filter(p=>p.ownerId!==actor.id);target._signatureParasites.push({ownerId:actor.id,turns:e.duration,drain:e.drain,maxHpRatio:Number(e.maxHpRatio||0)});actor._signatureSuccessful=true;signatureBonus(actor,state);}break;
 case 'visionary_hypnosis':if(target&&!statusImmune(target,'stunned')&&r()>=statusResistChance(target,'stunned')&&r()>=Number(combatRates(target.agent||target).resistance||0)){addStatus(target,'stunned',e.duration,actor.name);signatureBonus(actor,state);if(signatureSpend(actor,e,state,lines)){target._signatureCommand={ownerId:actor.id,multiplier:Number(e.commandMultiplier??1)};}}break;
 case 'darkness_nightmare':if(target&&hasStatus(target,'sleep')&&signatureSpend(actor,e,state,lines)){signatureDamage(actor,target,e.amount,'psychic',state,lines,r);signatureBonus(actor,state);}break;
 case 'death_summon':case 'paragon_device':case 'moon_beast':{const kind=e.rule==='death_summon'?'undead':e.rule==='moon_beast'?'beast':'device';const old=signatureUnits(state).find(u=>u.id===actor._signatureCompanionId&&u.alive);if(old&&signatureSpend(actor,e,state,lines)){old._signatureLifetime=e.duration;signatureHeal(actor,old,old.maxHp*.25,state,lines);}else signatureCreateCompanion(actor,state,lines,kind,e.duration,e.amount);signatureBonus(actor,state);break;}
 case 'giant_guardian':if(signatureSpend(actor,e,state,lines)){for(const ally of (redirect?[redirect]:allies)){const granted=grantShield(ally,ally.maxHp*e.amount);if(granted)emitCombatEvent(state,{type:'shield',actorId:actor.id,actorName:actor.name,actorTeam:teamOf(actor,state),targetId:ally.id,targetName:ally.name,targetTeam:teamOf(ally,state),amount:granted,shieldAfter:ally.shield||0});}signatureTimed(actor,'_signatureGuard',{turns:e.duration,amount:e.amount});}break;
 case 'red_war_command':if(signatureSpend(actor,e,state,lines)){for(const ally of allies)signatureTimed(ally,'_signatureWarFollow',{ownerId:actor.id,turns:e.duration,amount:e.amount});}break;
 case 'sun_purify':if(signatureSpend(actor,e,state,lines)){for(const ally of allies){let n=0;for(const st of ['poison','curse'])if(hasStatus(ally,st)&&n++<e.amount)removeStatus(ally,st);}if(target&&['darkness','death','demoness','abyss','hanged_man'].includes(target.path)){const ward=(target._fx||[]).find(f=>f.cat==='dtm'||(f.cat==='buff'&&f.key==='def'));if(ward){target._fx=target._fx.filter(f=>f!==ward);recomputeFx(target);}else if(target.shield>0){target.shield=0;delete target._shieldIncomingCategory;}}}break;
 case 'tyrant_soaked':for(const t of targets)if(t.alive)signatureTimed(t,'_signatureSoaked',{turns:e.duration,ownerId:actor.id});break;
 case 'tyrant_lightning':if(target?._signatureSoaked){delete target._signatureSoaked;signatureBonus(actor,state);const other=foes.find(t=>t!==target);if(other&&signatureSpend(actor,e,state,lines))signatureDamage(actor,other,e.amount,'lightning',state,lines,r);}break;
 case 'demoness_affliction':if(target&&agent.sequence<=5&&hasStatus(target,'curse')&&getMeterValue(agent,agent.path)>=e.chargeCost){const other=foes.find(t=>t!==target&&!hasStatus(t,'curse'));if(other&&signatureSpend(actor,e,state,lines)){addStatus(other,'curse',e.duration,actor.name,{signatureSpread:true});signatureBonus(actor,state);}}break;
 case 'fortune_retry':signatureTimed(actor,'_signatureRetry',{turns:e.duration,chargeCost:e.chargeCost});break;
 case 'fortune_calamity':for(const t of targets)signatureTimed(t,'_signatureCalamity',{ownerId:actor.id,turns:e.duration,amount:e.amount});break;
 case 'fortune_rewind':{const snapshot=(actor._signatureHistory||[]).findLast(h=>h.round<=(state.currentRound||1)-2);if(snapshot){if(snapshot.hp>actor.hp)signatureHeal(actor,actor,snapshot.hp-actor.hp,state,lines);else actor.hp=Math.max(1,snapshot.hp);actor._fx=cloneE(snapshot.fx||[]);recomputeFx(actor);signatureBonus(actor,state);signatureLog(actor,state,lines,`${actor.name} restores HP and temporary buffs from round ${snapshot.round}, preserving SP and cooldowns.`);}break;}
 case 'emperor_redirect':if(signatureSpend(actor,e,state,lines))signatureTimed(actor,'_signatureRedirect',{turns:e.duration});break;
 case 'justiciar_prohibition':for(const t of targets)signatureTimed(t,'_signatureProhibition',{ownerId:actor.id,turns:e.duration,amount:e.amount});break;
 case 'hanged_graze':actor._signatureGrazing=true;break;
 case 'hermit_scroll':if(!agent._signatureScroll){const learned=unlockedAbilities(agent).find(s=>signatureEligible({spec:s},agent,actor)&&(s.damage?.multiplier||s.scale||0)>0);if(learned)agent._signatureScroll={spec:cloneE(learned),sourceId:actor.id,sequence:signatureSourceRank(learned,actor)};}break;
 case 'mother_seed':{if(actor._signatureSeedTargetId){const old=signatureUnits(state).find(u=>u.id===actor._signatureSeedTargetId);if(old)delete old._signatureSeed;}const empowered=signatureSpend(actor,e,state,lines);signatureTimed(weakest,'_signatureSeed',{ownerId:actor.id,turns:e.duration,amount:e.amount*(empowered?2:1)});actor._signatureSeedTargetId=weakest.id;break;}
 case 'moon_medicine':actor._signatureMedicine=actor._signatureMedicine??2;signatureHeal(actor,weakest,weakest.maxHp*Number(e.maxHpRatio??.12),state,lines);if(signatureSpend(actor,e,state,lines)){actor._signatureMedicine=Math.min(2,actor._signatureMedicine+1);signatureHeal(actor,weakest,weakest.maxHp*e.amount,state,lines);}actor._signatureMedicine=Math.max(0,actor._signatureMedicine-1);break;
 case 'moon_blood':if(agent.sequence<=7&&signatureSpend(actor,e,state,lines))signatureHeal(actor,weakest,weakest.maxHp*e.amount,state,lines);break;
 case 'abyss_desire':if(target&&agent.sequence<=5){if(target._signatureDesire?.ownerId===actor.id&&signatureSpend(actor,e,state,lines)){signatureDamage(actor,target,e.amount,'fire',state,lines,r,agent.stats.int*e.amount+target._signatureDesire.paidSP);target._signatureDesire.paidSP=0;}signatureTimed(target,'_signatureDesire',{ownerId:actor.id,turns:e.duration,paidSP:target._signatureDesire?.paidSP||0});}break;
 case 'chained_release':if(hasStatus(actor,'curse')&&signatureSpend(actor,e,state,lines)){removeStatus(actor,'curse');if(target)signatureDamage(actor,target,0,'dark',state,lines,r,actor.maxHp*e.amount);}else addStatus(actor,'curse',e.duration,actor.name,{contained:true});break;
 default:throw new Error(`Unsupported signature ${e.rule}`);
 }
}
function signatureAfterCast(agent,actor,enemy,state,lines,r,spec,targets=[]){if(spec._signatureConsumeDistortion){delete actor._signatureDistortion;removeStatus(actor,'distorted_logic');}if(spec._signatureOwned)signatureLog(actor,state,lines,`${actor.name} uses ${spec._signatureOwned.replace(/_/g,' ')}: ${spec.name||spec.effectId}.`);if(spec._signatureChargeCost){changeMeter(agent,agent.path,-spec._signatureChargeCost);if(spec._signatureOwned==='record')agent._signatureRecords.shift();if(spec._signatureOwned==='scroll')agent._signatureScroll=null;if(spec._signatureOwned==='soul')agent._signatureSoul=null;}if(spec._signatureOwned==='error')agent._signatureBorrowed=null;if(spec._signatureOwned==='mythical_imitation')agent._signatureImitation=null;
 if(spec._signatureViolation){const judge=signatureUnits(state).find(u=>u.id===spec._signatureViolation&&u.alive);if(judge){signatureBonus(judge,state);const e=signatureRule({rule:'justiciar_prohibition'}),boost=signatureSpend(judge,e,state,lines)?2:1;signatureDamage(judge,actor,e.amount*boost,'holy',state,lines,r);signatureLog(judge,state,lines,`${actor.name}'s prohibited support fails and judgment is enforced.`);}}
 if(spec._signatureRedirectOwner){const owner=signatureUnits(state).find(u=>u.id===spec._signatureRedirectOwner);if(owner)delete owner._signatureRedirect;}
 if(actor._signatureDesire){actor._signatureDesire.paidSP+=Number(spec._signaturePaidSP??effectiveAbilityCost(agent,spec));const owner=signatureUnits(state).find(u=>u.id===actor._signatureDesire.ownerId);if(owner)signatureBonus(owner,state);}
 if(actor._signatureCalamity&&(spec.damage?.multiplier||spec.scale||0)>0&&!targets.length)signatureFailedAttack(actor,state,lines,r);
 if(spec._signatureMisfired||spec._signatureCancelled)return;
 const changed=actor._signatureBeforeDeception&&(signatureOwnDeceptionState(actor)!==actor._signatureBeforeDeception.own||foesOf(actor,state).some(u=>signatureDeceptionState(u)!==actor._signatureBeforeDeception.foes[u.id]));
 if(agent.path==='error'&&changed&&targets.length&&['combat_theft','deceptive_feint','logic_distortion','deceive_impact','steal_destiny_turn','time_theft','systemic_glitch'].includes(spec.effectId||spec.id)){actor._signatureSuccessful=true;signatureBonus(actor,state);}
 if(!actor.summoned&&agent.path==='hermit'&&agent.sequence<=6&&!spec._signatureOwned&&signatureEligible({spec},agent,actor)&&(spec.damage?.multiplier||spec.scale||0)>0&&!agent._signatureScroll)agent._signatureScroll={spec:cloneE(spec),sourceId:actor.id,sequence:signatureSourceRank(spec,actor)};
 if(!actor.summoned&&!spec._signatureOwned)for(const observer of foesOf(actor,state)){const a=getCombatAgent(observer);if(!observer.alive||observer.summoned)continue;if(a.path==='door'&&a.sequence<=6&&signatureEligible({spec},a,actor)){a._signatureRecords=a._signatureRecords||[];const cap=a.sequence===6?1:4;if(a._signatureRecords.length<cap&&!a._signatureRecords.some(x=>(x.spec.effectId||x.spec.id)===(spec.effectId||spec.id))){a._signatureRecords.push({spec:cloneE(spec),sourceId:actor.id,sequence:signatureSourceRank(spec,actor)});signatureLog(observer,state,lines,`${observer.name} witnesses and records ${spec.name||spec.effectId}.`);}changeMeter(a,'door',Number(PATH_METERS.door.gainAction??20));signatureBonus(observer,state);}if(a.path==='white_tower'||a.path==='visionary')signatureBonus(observer,state);}
 const actual=(state.events||[]).slice(actor._signatureEventStart||0).some(ev=>ev.actorId===actor.id&&((ev.type==='heal'&&ev.amount>0)||(ev.type==='status'&&/cleanses/.test(ev.text||''))));if(actual&&['mother','moon','sun'].includes(agent.path))signatureBonus(actor,state);
}
function signatureAfterDamage(attacker,defender,result,state,lines,r,opt={}){if(!state||opt.signature)return;if(attacker?.alive&&(result.hpLoss+result.absorbed)>0){const a=getCombatAgent(attacker);if(['tyrant','red_priest','sun','hermit','paragon','abyss'].includes(a.path))signatureBonus(attacker,state);const follow=attacker._signatureWarFollow;if(follow&&!opt.indirect&&!opt.reflect){delete attacker._signatureWarFollow;const owner=signatureUnits(state).find(u=>u.id===follow.ownerId&&u.alive);if(owner&&defender.alive)signatureDamage(owner,defender,0,'physical',state,lines,r,getCombatAgent(owner).stats.atk*follow.amount);}}
 if(defender?.alive&&(result.hpLoss+result.absorbed)>0){const a=getCombatAgent(defender);if(['twilight_giant','chained','wheel_of_fortune'].includes(a.path))signatureBonus(defender,state);if(defender._signatureGuard&&attacker?.alive&&!opt.indirect&&!opt.reflect){delete defender._signatureGuard;signatureDamage(defender,attacker,0,'physical',state,lines,r,a.stats.atk*.5);}}
 if(opt.indirect&&defender?.statusMeta?.curse&&!defender.statusMeta.curse.signatureSpread){const owner=signatureUnits(state).find(u=>u.id===defender.statusMeta.curse.source||u.name===defender.statusMeta.curse.source);if(owner?.path==='demoness')signatureBonus(owner,state);}
}
function signatureFailedAttack(actor,state,lines,r){if(!actor?._signatureCalamity||!actor.alive)return;const turn=state?.currentTurn||0;if(actor._signatureBacklashTurn===turn)return;const owner=signatureUnits(state).find(u=>u.id===actor._signatureCalamity.ownerId&&u.alive);if(!owner)return;actor._signatureBacklashTurn=turn;signatureDamage(owner,actor,0,'psychic',state,lines,r,getCombatAgent(actor).stats.int*actor._signatureCalamity.amount);signatureBonus(owner,state);}
function signatureTryAction(unit,state,lines,r){const command=unit?._signatureCommand;if(!unit?.alive||!command)return false;delete unit._signatureCommand;removeStatus(unit,'stunned');const target=sameSideOf(unit,state).find(u=>u!==unit&&u.alive&&u.inCombat!==false&&!hasStatus(u,'untargetable'));if(target)signatureDamage(unit,target,command.multiplier,'psychic',state,lines,r);signatureLog(unit,state,lines,`${unit.name}'s commanded action is consumed${target?` against ${target.name}`:''}.`);return true;}
function signatureTurnStart(unit,state,lines,r){if(!unit.alive)return;if(unit._signatureSeed){const owner=signatureUnits(state).find(u=>u.id===unit._signatureSeed.ownerId&&u.alive);if(owner)signatureHeal(owner,unit,unit.maxHp*unit._signatureSeed.amount,state,lines);}
 for(const parasite of unit._signatureParasites||[]){const owner=signatureUnits(state).find(u=>u.id===parasite.ownerId&&u.alive);if(!owner)continue;const victim=getCombatAgent(unit),a=getCombatAgent(owner),drained=Math.min(parasite.drain,victim.sp||0);victim.sp-=drained;unit.sp=victim.sp;a.sp=Math.min(a.maxSP,(a.sp||0)+drained);owner.sp=a.sp;if(drained){signatureHeal(owner,owner,owner.maxHp*Number(parasite.maxHpRatio||0),state,lines);signatureBonus(owner,state);signatureLog(owner,state,lines,`${owner.name}'s parasite siphons ${drained} SP from ${unit.name}.`);}}
 if(unit._signatureCompanionKind==='device'){const owner=signatureUnits(state).find(u=>u.id===unit._signatureOwnerId&&u.alive);if(owner&&owner.hp<owner.maxHp*.5)grantShield(owner,owner.maxHp*.08);}
}
function signatureTurnEnd(unit,state,lines,r){if(!unit)return;if(unit.path==='wheel_of_fortune'&&!unit.summoned){unit._signatureHistory=unit._signatureHistory||[];unit._signatureHistory.push({round:state?.currentRound||1,hp:unit.hp,fx:cloneE(unit._fx||[])});unit._signatureHistory=unit._signatureHistory.slice(-4);}
 for(const key of ['_signatureDistortion','_signatureSoaked','_signatureGuard','_signatureWarFollow','_signatureSeed','_signatureRetry','_signatureCalamity','_signatureRedirect','_signatureProhibition','_signatureDesire','_signatureParasite'])if(unit[key]){if(unit._signatureGrace?.[key])delete unit._signatureGrace[key];else if(--unit[key].turns<=0){delete unit[key];if(key==='_signatureDistortion')removeStatus(unit,'distorted_logic');}}
 for(const id of Object.keys(unit._signatureDeniedSkills||{}))if(--unit._signatureDeniedSkills[id]<=0)delete unit._signatureDeniedSkills[id];unit._signatureParasites=(unit._signatureParasites||[]).filter(p=>--p.turns>0);
 if(unit._signatureCompanionId){const companion=signatureUnits(state).find(u=>u.id===unit._signatureCompanionId);if(companion&&!companion.alive)delete unit._signatureCompanionId;}
 if(unit._signatureLifetime&&unit._signatureCompanionKind!=='historical_machine'&&--unit._signatureLifetime<=0){unit.alive=false;unit.inCombat=false;signatureLog(unit,state,lines,`${unit.name}'s temporary vessel expires.`);}delete unit._signatureCommand;
}
function signatureFinalDeath(unit,source,state,lines,r){if(!state||unit.alive)return;if(unit._signatureFinalSettled)return;unit._signatureFinalSettled=true;for(const owner of foesOf(unit,state)){if(!owner.alive||owner.summoned)continue;if(owner.path==='hanged_man'&&owner.sequence<=5&&(owner._signatureGrazing||source?.id===owner.id))signatureCaptureSoul(owner,unit,state,lines);if(owner.path==='death')signatureBonus(owner,state);}}
function signatureActionFinished(unit,state,lines,r){if(!unit?.alive||unit.summoned)return;const a=getCombatAgent(unit);if(!a.path||!a.awakened)return;if(a.path==='door')return;if(a.path==='error'&&!unit._signatureSuccessful)return;changeMeter(a,a.path,Number(PATH_METERS[a.path]?.gainAction??20));if(a.path==='error'){signatureBonus(unit,state);delete unit._signatureSuccessful;}}
function signatureRetryContest(actor,state,lines,r,chance,failed,forced=false){if(!failed||forced||actor.path!=='wheel_of_fortune'||!actor._signatureRetry)return !failed;const e=signatureRule({rule:'fortune_retry',chargeCost:actor._signatureRetry.chargeCost});if(!signatureSpend(actor,e,state,lines))return false;delete actor._signatureRetry;signatureLog(actor,state,lines,`${actor.name} retries one failed contest at its original chance.`);return r()>=chance;}
